debug: add some logging

diff --git a/.github/workflows/bump-release.yml b/.github/workflows/bump-release.yml
--- a/.github/workflows/bump-release.yml
+++ b/.github/workflows/bump-release.yml
@@ -58,6 +58,11 @@ jobs:
       - name: Compute Next Tag
         run: |
           git_next_tag="$(docker run --rm -e GITHUB_VERSION_INPUT -e GITHUB_VERSION_BUMP ghcr.io/${{ github.repository }}:${{ github.sha }})"
+          if [[ -z "$git_next_tag" ]]; then
+            echo "Failed to compute next tag"
+            docker run --rm -e GITHUB_VERSION_INPUT -e GITHUB_VERSION_BUMP ghcr.io/${{ github.repository }}:${{ github.sha }})
+            exit 1
+          fi
           echo "GIT_NEXT_TAG=$git_next_tag" >>"$GITHUB_OUTPUT"
         env:
           GITHUB_VERSION_INPUT: ${{ steps.latest-tag.outputs.GIT_LATEST_TAG }}
